In [16]:
import numpy as np
import pandas as pd

# Create a 3x3 matrix
A = np.arange(21, 30).reshape(3, 3)

# Print the matrix
print('A = ', A)

# Take the transpose
print('A^T = ', A.transpose())

B = np.arange(31, 40).reshape(3, 3)

# Matrix dot multiplication
AB = A.dot(B)
BA = B.dot(A)
print('AB = ', AB)
print('BA = ', BA)

C = np.arange(41, 50).reshape(3, 3)

# Associativity holds
temp1 = (A.dot(B)).dot(C)
temp2 = A.dot(B.dot(C))
print('(AB)C = ', temp1)
print('A(BC) = ', temp2)

A =  [[21 22 23]
 [24 25 26]
 [27 28 29]]
A^T =  [[21 24 27]
 [22 25 28]
 [23 26 29]]
AB =  [[2250 2316 2382]
 [2556 2631 2706]
 [2862 2946 3030]]
BA =  [[2310 2406 2502]
 [2526 2631 2736]
 [2742 2856 2970]]
(AB)C =  [[306108 313056 320004]
 [347742 355635 363528]
 [389376 398214 407052]]
A(BC) =  [[306108 313056 320004]
 [347742 355635 363528]
 [389376 398214 407052]]


In [23]:
# Create a 4x4 matrix
arr = np.arange(100, 116).reshape(4, 4)
print('arr = ', arr)

# Find the determinant
# Website's answer (something e-31) is different from mine (something e-27), but output is close to 0. Seems like a
# floating point rounding error.
print('det(arr) = ', np.linalg.det(arr))

arr1 = np.arange(5, 21).reshape(4, 4)

# Find the inverse
print('arr1 = ', arr1)
print('arr1^-1 = ', np.linalg.inv(arr1))
# Inverse has very large numbers. This seems to be another floating point rounding error. Wolfram Alpha says the matrix
# is singular (not invertible).

arr =  [[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]
det(arr) =  -2.42338070084e-27
arr1 =  [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
1.37557620348e-29
arr1^-1 =  [[ -9.68516049e+14   1.74332889e+15  -5.81109629e+14  -1.93703210e+14]
 [  1.96931597e+15  -3.24452876e+15   5.81109629e+14   6.94103168e+14]
 [ -1.03308379e+15   1.25907086e+15   5.81109629e+14  -8.07096707e+14]
 [  3.22838683e+13   2.42129012e+14  -5.81109629e+14   3.06696749e+14]]


In [30]:
Df = pd.read_csv('baseball.csv')
Df1 = Df.head(14)

X = Df1[['RS', 'RA', 'W', 'OBP', 'SLG', 'BA']]
Y = Df1['OOBP']

X = np.asmatrix(X)
x = np.transpose(X)
T = x.dot(X)
inv = np.linalg.inv(T)
theta = (inv.dot(X.T)).dot(Y)
print(theta)

[[ -2.59951184e-04   1.53102522e-04  -6.98603725e-05   6.57605847e-01
    4.00767706e-01   1.07696279e-01]]


In [32]:
arr = np.arange(1, 10).reshape(3, 3)

print('Eigenvalues and eigenvectors: ', np.linalg.eig(arr))

Eigenvalues and eigenvectors:  (array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
